### ISSUE TITLE
Animation on repeat speeds up over time.

### ISSUE THREAD

**Issue by trusktr** [tweenjs/tween.js#378]
Here's @jonobr1's original, forked to use array values:

https://codepen.io/trusktr/pen/04518ee24a8d1d7822e584c6a513d378?editors=1010

Watch it for a while. Over time, the animation speeds up, which shouldn't happen.

**Comment by jonobr1** [comment]
Do you know what the bug I'm leveraging is?

**Comment by trusktr** [comment]
@jonobr1 Oops, I meant to post a link to a fork of yours, where the only difference is that I'm passing an array of values to `o`'s `to` `rotation`, on line 10:

http://jsfiddle.net/18ymqpdw/0/

If you watch it for a while, you'll notice that the animation seems to speed up after a few repeats.

I updated the original post to use the forked link. What bug were you leveraging in [yours](
http://jsfiddle.net/jonobr1/72bytkhm/)?

**Comment by jonobr1** [comment]
I'm not too familiar with arrays in Tween.js..., but if that's the difference then I don't think I'm leveraging any bugs in the fiddle I made. Also, this might be an inaccurate use of the API and may not be a bug.

**Comment by dalisoft** [comment]
@trusktr See [fiddle](http://jsfiddle.net/s8bjk6r0/1/) using es6-tween, but it has bug also

**Comment by trusktr** [comment]
Interesting, at least that behavior is consistently repeating, rather than changing each time it repeats. Let's see what's going on here..

**Comment by dalisoft** [comment]
@trusktr It is about tween.js or es6-tween. I am added this to es6-tween issue list and i will fix as soon as possible

**Comment by dalisoft** [comment]
@trusktr Is in this [fiddle](http://jsfiddle.net/18ymqpdw/3/) issue was fixed?

**Comment by trusktr** [comment]
Looks like the examples broke. I update the OP with a working example on codepen. I'd like to start fixing stuff and moving forward!

**Comment by trusktr** [comment]
@dalisoft Mind updating your example?

Also, sidenote, if you don't mind making some PRs to bring your ideas into the main repo, that'd be great!

**Comment by dalisoft** [comment]
@trusktr I [updated](http://jsfiddle.net/64vdmw7u/), but seems does not work, some incompatibility with two.js

I deprecated es6-tween due of less time to spent, i think these some things can be applied and source code can be got from es6-tween

- TypeScript (currently es6-tween is ES6, but before have been written TS)
- DOM Plugins
- Infinite Deep-Level tweening without loss of performance
- Events (multiple `.on('complete' | 'update', 'start')`)

**Comment by trusktr** [comment]
@dalisoft Thanks! I updated your example with the working version of Two.js: https://codepen.io/trusktr/pen/b10d7a5693b7ba6b9ed70b13e7ab0fb2?editors=1010

I like those ideas. In particular I'm curious about `Infinite Deep-Level tweening without loss of performance`. I just merged and updated outstanding nested properties pull requests from @Malows and @talltyler. See https://github.com/tweenjs/tween.js/pull/536 and https://github.com/tweenjs/tween.js/pull/366

Interested to learn about the alternative method. I'm thinking perhaps to cache the nested objects to key paths. What'd you do in es6-tween?

**Comment by trusktr** [comment]
Updated the broken example with newest changes. No luck though: https://codepen.io/trusktr/pen/c258027326d412f81e3aad96d669307c?editors=1010 Need to dig into it...

**Comment by trusktr** [comment]
@dalisoft In which commit did you fix the bug in es6-tween?

**Comment by dalisoft** [comment]
@trusktr Which bug? I don’t remember, there but more commits, really I don’t have time to checkout all them. 
Of course, if you mean infinite deep level tweening - it’s not bug, i made it feature from start of planning es6-tween. 
Most of tweening library still does not support this feature

**Comment by trusktr** [comment]
I meant the bug that the above demo goes faster and faster over time. I'll peruse through es6-tween next.

**Comment by dalisoft** [comment]
I don’t think i can support es6-tween anymore currently and within few month. 
Of course, it’s off-topic, but did you got my mail message?

**Comment by trusktr** [comment]
Looks like this is still reproducible in v22, and in particular it looks like it happens with the new `startFromCurrentValues()` method which used to be the default behavior in v16.6:

https://codepen.io/trusktr/pen/oNVBjKG/ff650c9a627e22bb629cdae20b8eaec4?editors=1010

**Comment by trusktr** [comment]
Array values will be deprecated, and removed. Tween has gotten to complex trying to do too many things, each thing inflexible and hard to update, and error prone.

In place of array values will be a decoupled Curve/Path API, tracked in

- #721 

A Tween does not need to know about the concept of a path. It just needs to animate an easing curve from start to finish, between two values. A Tween animated from 0 to 1 can be used to index a position into a separate Path or Curve to animate along a path/curve.
